### ISSUE TITLE
Tests seem to be going into infinite loop

### ISSUE THREAD

**Issue by ViralBShah** [felipenoris/BusinessDays.jl#4] opened 2016-09-03 07:24 UTC
The tests seem to be going into an infinite loop. I discovered this trying to troubleshoot https://github.com/JuliaLang/julia/pull/18276

Reporting here in case it is an issue with this package for 0.5. If it is a julia problem, would be good to know.

**Comment by felipenoris** [comment] 2016-09-04 00:50
Looks like a problem with julia's codegen.
The test runs, but takes a lot of time. I tested using `tk/backports-0.5.0-rc4` branch.
Once it reaches line 285 in `runtests.jl` it takes a while to start the loop.

``` julia
for usecache in [false, true]
```

If, for instance, I change the line 285 to :

``` julia
usecache = false
```

and comment the line 825

``` julia
#end
```

the problem is solved.

**Comment by ViralBShah** [comment] 2016-09-04 06:33
Could you file an issue in the julia repo, if it is a performance regression?

Cc @jeffbezanson @vtjnash @tkelman

**Comment by felipenoris** [comment] 2016-09-21 20:02
Ref https://github.com/JuliaLang/julia/issues/18077

**Comment by felipenoris** [comment] 2017-09-25 20:40
I´ll close this for now, since v0.6 got this a lot better.

**Closed as completed by felipenoris** 2017-09-25 20:40 UTC
Labels: upstream
